import { Inter } from "next/font/google";
import "./Assets/css/bootstrap.min.css"
import "./globals.css";
import "./Assets/css/responsive.css"
import { Providers } from "./Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "AgriBevy",
  description: "Generated by create next app",
};  

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Providers>
      <body className={inter.className}>{children}</body>
     
      </Providers>
      
    </html>
  );
}
